/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class park_tt_com_parking_model_Graph */

#ifndef _Included_park_tt_com_parking_model_Graph
#define _Included_park_tt_com_parking_model_Graph
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     park_tt_com_parking_model_Graph
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_park_tt_com_parking_model_Graph_init
  (JNIEnv *, jobject);
  
  

/*
 * Class:     park_tt_com_parking_model_Graph
 * Method:    destory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_park_tt_com_parking_model_Graph_destory
  (JNIEnv *, jobject);


/*
 * Class:     park_tt_com_parking_model_Graph
 * Method:    addVertex
 * Signature: (ILjava/util/List;)V
 */
JNIEXPORT void JNICALL Java_park_tt_com_parking_model_Graph_addVertex
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     park_tt_com_parking_model_Graph
 * Method:    getShortestPath
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_park_tt_com_parking_model_Graph_getShortestPath
  (JNIEnv *, jobject, jint start, jint finish);

#ifdef __cplusplus
}
#endif
#endif
